### ISSUE TITLE
Alignment no more working

### ISSUE THREAD

**Issue by MasterPIC** [charleslemaire0/TeenAstro#66] opened 2023-05-07 05:45 UTC
I just tested current release 1.4 branch on the field on my equatorial mount and I found that PC alignment doesn't work anymore.
As soon as I activate PC alignment, just one sync (by PC) makes the SHC showing the alignment icon and the  coordinates are wrong.
The same issue occurs also when trying to align by SHC. As soon as the first alignment sync occurs (after the the first star has been manually centred by SHC) coordinates are wrong and alignment fails.

**Comment by charleslemaire0** [comment] 2023-05-09 17:42
your fix has been merged

**Comment by MasterPIC** [comment] 2023-05-09 19:15
Alignment still doesn't work. Other fixes are required.

**Comment by charleslemaire0** [comment] 2023-05-09 19:24
ok


Am Di., 9. Mai 2023 um 21:15 Uhr schrieb MasterPIC ***@***.***

**Comment by charleslemaire0** [comment] 2023-05-10 17:31
Hi Armando,

If I perform a 2 Star alignment I have no issue with the SHC
are you doing a 3 Star alignment?

**Comment by MasterPIC** [comment] 2023-05-11 00:17
Also by a 2 stars alignment you can see that the coordinates at the end of the alignment differ from the ones of the 2nd star.
You can double check by a sync on the 2nd star at the end of the alignment: coordinates will change...

**Comment by charleslemaire0** [comment] 2023-05-11 17:57
Hi,
I commited a fix, I checked with the SkySimulator could you check that it
is also ok for you
Charles

Am Do., 11. Mai 2023 um 02:17 Uhr schrieb MasterPIC <
***@***.***>:

**Comment by charleslemaire0** [comment] 2023-05-11 18:47
sorry it still doesn't work

Am Do., 11. Mai 2023 um 19:57 Uhr schrieb Charles Lemaire <
***@***.***>:

**Comment by MasterPIC** [comment] 2023-05-11 18:52
I just checked (both 2 stars and 3 stars alignment). I confirm it still doesn't work.

**Comment by charleslemaire0** [comment] 2023-05-15 18:57
Hi Armando, could you update and test. think it should work now. Please modify your axis1 limit : -270° to 90° is the valid range

**Comment by MasterPIC** [comment] 2023-05-15 19:07
I'm just checking. I'll let you know ASAP

**Comment by MasterPIC** [comment] 2023-05-15 19:15
At the end of a 2 stars alignment by SHC, coordinates are right also if I simulate  a bad alignment.
But I'm having an error about target outside limits if I select Beta UMi (actually about Alt. 50deg, Az. 18deg). I selected it as 1st star to test alignment by pointing to the other side of the pier...

**Comment by charleslemaire0** [comment] 2023-05-15 19:38
Yes you have to modify the limit

**Comment by charleslemaire0** [comment] 2023-05-15 19:39
Ok I get it too

Le lun. 15 mai 2023, 21:38, Charles Lemaire ***@***.***> a
écrit :

> Yes you have to modify the limit
>

**Comment by charleslemaire0** [comment] 2023-05-16 18:14
Hi
it should be fixed now

Am Mo., 15. Mai 2023 um 21:39 Uhr schrieb Charles Lemaire <
***@***.***>:

**Comment by MasterPIC** [comment] 2023-05-16 20:33
I can't set Axis 1 max greater than 90 deg. So a sync to UMi Beta makes the SHC reporting A1 limits error...

**Comment by charleslemaire0** [comment] 2023-05-16 20:37
Yes this right

The min is about -270 and max 90
Charles

**Comment by charleslemaire0** [comment] 2023-05-16 20:39
The root cause of the problem is that in the previous math model the
instrument pole was at 90 degrees for axis 1 but with the new model it is
at -90 degrees

Le mar. 16 mai 2023, 22:36, Charles Lemaire ***@***.***> a
écrit :

> Yes this right
>
> The min is about -270 and max 90
> Charles
>

**Comment by MasterPIC** [comment] 2023-05-17 20:12
I see that slewing to UMi beta (or a sync to it from the right pier side) works as expected now.
So everything seems to work now. I see just the need for updating web server as 360 is the max allowed value according to the label (the same for SHC). In any case max value is set to 90, so just a UI fix...

**Comment by MasterPIC** [comment] 2023-05-17 20:27
I checked a new 3 stars alignment on UMi and Hercules by SHC. At the end of the alignment coordinates are wrong.
Previously during the alignment by SHC, on each star (after recentring) coordinates were updated as expected. Now if I simulate a bad alignment, at the end of each recentring step coordinates stay wrong (and at the end of the alignment the controller reports to point far from the expected position - I'd expect the controller pointing to the 3rd star)...

**Comment by charleslemaire0** [comment] 2023-08-08 11:42
Hello,

As the new pipeline only work with euler angle I see currently no chance to support the TAKI AFFINE transformation.
Here are the reason I will remove this feature:
1. Anyway modern software have plate solver
2. the 3 point alignment doesn't correct misalignment anywehre on the sky
3. it doesn't correct cone error

I introduced the 3 Stars alignment for the last error.
The PC alignment will require only 2 stars and not 3 like in the past

This will be fixed soon

**Closed** 2023-08-16 11:06 UTC
